Edit ride in the back office
Ezer-Lachaim/EZLA pull request #293
Opened 2023-11-12 08:44 UTC by IsraelKariti

Add Edit button to the rides in the back office
populate all the fields in the Edit Ride modal with their respective values update in the database

2023-11-13 19:02 UTC, iddanh requested changes
חוץ מזה נראה טוב, אחרי שתתקן את ההערות האלה אפשר למרגג

2023-11-13 19:02 UTC, iddanh commented on client/src/Backoffice/components/Main/components/modals/EditRideModal/EditRideModal.tsx
> +    };
כשבדקתי את זה השעה של הנסיעה מתרסטת:
![image](https://github.com/Ezer-Lachaim/EZLA/assets/12518219/38da746b-f13d-403e-b522-16876c516202)

לדעתי אם תוריד את השורה הזאת זה יסתדר:
```suggestion
      rideId: ride.rideId
    };
```

2023-11-14 06:33 UTC, iddanh approved these changes

2023-11-14 06:33 UTC, merged

2023-11-15 15:33 UTC, LEVI-RIVKIN commented
@iddanh @IsraelKariti נראה לי שזה משהו שהיה צריך להיעשות ב main branch

2023-11-16 08:44 UTC, iddanh commented
צודק, אפשר לראות בהיסטוריה שניסיתי לשנות את הbase branch של הpr הזה לmain, אבל זה יצר יותר מדי קונפליקטים.

@IsraelKariti
 אולי תוכל ליצור עוד pr עם התיקון הזה עבור main?

2023-11-16 13:34 UTC, IsraelKariti commented
כן, יצרתי על זה טיקט לעצמי, אבל יקח זמן להגיע לזה