#282 Edit Driver in back office
Ezer-Lachaim/EZLA pull request #314
Opened 2023-11-18 16:28 UTC by IsraelKariti

1. create a router + controller + api call for the updating of the data in the db
2. create the modal + info components for updating the driver
3. add "Edit" button to table

2023-11-19 14:01 UTC, iddanh commented
@IsraelKariti This PR should be to `main` branch I think

2023-11-19 14:34 UTC, IsraelKariti commented
ניסיתי עכשיו, ונוצרו יותר מדי קונפליקטים עם קוד שאני לא מכיר, מעדיף שזה ישאר בopen to all

2023-11-19 14:57 UTC, iddanh requested changes
@IsraelKariti Tried it locally and got an error when submitting:
![image](https://github.com/Ezer-Lachaim/EZLA/assets/12518219/e6eac85a-a9a5-4a22-bb2e-08320aababca)

Looks like you forgot to update the `openapi.yaml` file with the new updateDriver endpoint

2023-11-20 10:48 UTC, IsraelKariti commented
It seems that .gitignore specify the api-client directory since the api-client is a generated code.
Therefore I can't include the changes i have made to DriverApi.ts which is inside the api-client directory (namely the updateDriver function)
1. Should we changed .gitignore?
2. Should the updateDriver be generated automatically somehow?
3. Should the .yaml be updated automatically as well?

2023-11-20 15:06 UTC, iddanh commented
This code is indeed autogenerated and should not be committed. It is generated based on the code in the yaml file, so you should make your updates there and commit them

2023-11-21 15:08 UTC, IsraelKariti commented
@iddanh First time i encounter autogeneration, very cool concept, thank you, I have now updated the .yaml file

2023-11-22 11:40 UTC, iddanh requested changes
Much better, mostly works now except for one bug

2023-11-22 11:40 UTC, iddanh commented on client/src/Backoffice/components/Main/components/modals/EditDriverModal/EditDriverCarInfo/EditDriverCarInfo.tsx
> +  }, [driver, setValue]);
When I tried it, modifying these values did not work. Whey did you need this useEffect?

2023-11-23 21:19 UTC, IsraelKariti commented
@iddanh You are right, I have now deleted useEffect. It was a leftovers from some previous trial and error

2023-11-29 07:36 UTC, iddanh approved these changes

2023-11-29 07:36 UTC, merged

2023-11-29 07:37 UTC, iddanh commented
@IsraelKariti we probably want these changes also in `main` branch. Can you do a new PR and cherry pick these commits?