Enlarge font size in fields and hint text - across the board
Ezer-Lachaim/EZLA pull request #367
Opened 2024-01-03 19:02 UTC by YankiBaras

2024-01-07 11:34 UTC, yitshak approved these changes
הראה טוב. להבא, יש לשקול השנות את הקוד קח השינוי יהיה ממקום אחד (סטייל משותף)

2024-01-07 11:36 UTC, yitshak requested changes
צריך לפתור את הקונפליקטים.

2024-01-07 11:36 UTC, yitshak commented on package-lock.json
>          "backend-mock"
כל השינויים בקובץ הזה נחוצים לתיקון שלך? אם כן יש לפתור את הקונפליקטים

2024-01-07 12:27 UTC, YankiBaras commented
> הראה טוב. להבא, יש לשקול השנות את הקוד קח השינוי יהיה ממקום אחד (סטייל משותף)
עשיתי בצורה הזאת משום שהפונט צריך להשתנות רק בקומפוננטה הספציפית הזאת, ולא בכל הפרויקט

2024-01-07 12:27 UTC, YankiBaras commented on package-lock.json
>          "backend-mock"
אין צורך בשום שינוי בpackage.json 
יש לדחות את כל השינויים בקובץ הזה

2024-01-07 12:29 UTC, YankiBaras commented
דיברתי עם אורלי והיא ביקשה לשנות גם את גודל הפונט של הכפתור התחתון, ביצעתי את השינוי. איך לשלוח את השינויים?

2024-01-14 21:05 UTC, yitshak commented on package-lock.json
>          "backend-mock"
כדי שאני אוכל לדחות קובץ עליי להוריד אליי את המרג' ריקווסט, ולהוריד את השינויים. אבקש שפעם הבאה תתקן את המרג' ריקווסט.

2024-01-14 21:26 UTC, yitshak requested changes
יעקב, אני לא יכול לאשר להכניס את השינויים ככה. אתה צריך לתקן את כל הקונפליקטים ולעשות את התיקונים שאורלי ביקשה. אם תרצה נוכל לדבר על זה מחר.

2024-01-17 10:38 UTC, closed without merging