Issue 413
Ezer-Lachaim/EZLA pull request #444
Opened 2024-02-18 13:31 UTC by YankiBaras

closes #431

2024-02-18 17:24 UTC, yitshak approved these changes
LGTM

2024-02-18 17:27 UTC, yitshak requested changes
יש פה בעיה, איך כל השינויים האלה קשורים לקו-התחתי. נראה לי שלא יצאת מ main/

2024-02-18 18:33 UTC, YankiBaras commented
> יש פה בעיה, איך כל השינויים האלה קשורים לקו-התחתי. נראה לי שלא יצאת מ main/

אכן השינויים הללו לא קשורים רק לקו התחתי. זהו בראנץ' שלם שמיועד לסגנן את הבקאופיס בהתאם להגדרות בפיגמה, וביטול הקו התחתון הוא רק אחד מהם.

2024-02-20 06:56 UTC, yitshak commented
היי יעקב, יש פה בלאגן יש קונפליקטים שלא מאפשרים לעשות ריבייס

2024-02-20 11:32 UTC, yitshak approved these changes
LGTM

2024-02-20 11:32 UTC, merged